# Site settings

title: TLDR pages
description: Simplified and community-driven man pages
moto: Help and manual for human beings.
github_org: tldr-pages
github_repo: tldr
github: https://github.com/tldr-pages/tldr


# Build settings

markdown: kramdown
exclude: ["README.md"]
